const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#2563eb",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#f9f9f9",
    cardForeground: "#0a0a0a",
    primary: "#2563eb",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f0",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f0f0",
    mutedForeground: "#737373",
    accent: "#f0f0f0",
    accentForeground: "#1a1a1a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    warning: "#f59e0b",
    success: "#22c55e",
    border: "#e5e5e5",
    input: "#e5e5e5",
  },
  dark: {
    text: "#fafafa",
    tint: "#a855f7",
    background: "#09090b",
    foreground: "#fafafa",
    card: "#111115",
    cardForeground: "#fafafa",
    primary: "#a855f7",
    primaryForeground: "#ffffff",
    secondary: "#1c1c1f",
    secondaryForeground: "#fafafa",
    muted: "#1c1c1f",
    mutedForeground: "#a1a1aa",
    accent: "#9333ea",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    warning: "#f59e0b",
    success: "#22c55e",
    border: "#27272a",
    input: "#1c1c1f",
  },
  radius: 12,
};

export default colors;
